services:
  mysql:
    build:
        context: ./docker/database/mysql
    container_name: http-skeleton-database
    restart: unless-stopped
    env_file:
      - .env
    ports: ["3306:3306"]
    tty: true
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1", "-u app", "-pth3p4ssw0rd"]
        interval: 2s
        timeout: 20s
        retries: 10


  app:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: http-skeleton-go
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}/:/var/www/html"
      - ./database:/app/database
    depends_on:
       mysql:
        condition: service_healthy
