name: http-skeleton-go

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install docker-compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build app
        run: |
          make install
          bash scripts/seed_db.sh

      - name: Wait for server
        run:        |
          cp .env.example .env
          go mod tidy
          sleep 10
          for i in {1..10}; do
          if curl -s http://localhost:8080/healthz; then
            echo "App is up!"
            break
          fi
          echo "Waiting for app..."
          sleep 2
          done

      - name: Run acceptance tests
        run:  |
                  go run ./src/user-interface/cmd/main.go &
                  APP_PID=$!
                  sleep 2
                  go test -v ./tests/acceptance/...
                  kill $APP_PID